# -*- coding: utf-8 -*-
"""nanobanana.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wApXaHIbfWTewyGwQuwyQ7i5mKBoQsSW
"""

from google.colab import userdata

GOOGLE_API_KEY = "your gemini api key"

from google import genai
from google.genai import types

client = genai.Client(api_key=GOOGLE_API_KEY)

model= "gemini-2.5-flash-image-preview"

from IPython.display import display, Markdown, Image
import pathlib


def display_response(response):
  for part in response.parts:
    if part.text:
      display(Markdown(part.text))
    elif image:= part.as_image():
      display(image)

def save_image(response, path):
  for part in response.parts:
    if image:= part.as_image():
      image.save(path)

prompt = "spiderman doing coding with ironman"

response = client.models.generate_content(
    model=model,
    contents=prompt,
    config=types.GenerateContentConfig(
        response_modalities=['Text', 'Image']
    )
)

display_response(response)
save_image(response, 'spiderman.png')

prompt = "A slice pizza wearing googles ,hopping between ancient rome year 325"

response = client.models.generate_content(
    model=model,
    contents=prompt,
)

display_response(response)

prompt="""create a photo visualizing serene yoga poses of Spiderman in a natural setting promoting mental and physical well-being."""

response = client.models.generate_content(
    model=model,
    contents=prompt,
)

display_response(response)

prompt="""spiderman doing coding machine learning and on llm concept"""
response = client.models.generate_content(
    model=model,
    contents=prompt,
)

display_response(response)

prompt="""spiderman working as data scientist whose teamlead is ironman"""
response = client.models.generate_content(
    model=model,
    contents=prompt,
)

display_response(response)

